### PR TITLE
FDM friendly M3 screw version

### PR DESCRIPTION
**Pull request by Myles512**
Hi, wanted to submit a modification I made to this to make it friendlier to print on FDM. I didn't make any documentation for it, but it swaps supports and post processing for 3 M3 x 20 shcs screws.

### CODE REVIEW

**Comment by jakemcivor** [comment]
Hey @Myles512 - thanks for submitting the PR. 

Have you printed out and tested this version? I'm wondering how well the two halves remain together near the hook portion and at the back near the strap/hanging hole.

Are the screws sufficient here, or should adhesive be used as well?

One advantage of this split approach is that a much more ergonomic round/fillet could be added to the edge that wouldn't be possible in the original print orientation. The hook should also be much stronger.
 
The primary disadvantage is the need for tools and hardware - especially as M3 cap screws can be tricky to find in small quantities. 

Some octagonal 3D printed pins could be used in addition to the screws, or possibly in place of, with a suitable adhesive.    

Assuming this one has been tested and functions similarly to the original, happy to add this as a variant.

**Comment by Myles512** [comment]
I've printed and tested, but to be quite honest, I don't actually know how the tool works. :sweat_smile: I ended up deforming the little hook that goes underneath the jar. It's possible that hook could be made stronger, but I didn't want to fiddle with it until I figured out how it's supposed to be used.

I did not use adhesives, and the back hook hole seems to require a significant amount of force to separate.
PXL_20240411_161147146

I designed for cap screws, but it would be easy to widen the screw head hole to accommodate larger screw heads, or just change it to use different more commonly available screws altogether. I just happen to have a lot of m3's on hand because I build my own printers. Also, I left the original files in place, so that people could choose to use either version if they didn't have screws/tools on hand.

You're right about the fillets. I didn't want to change too much about the original design to start with, but that is an easy change. I also enlarged the screw holes a tiny bit on the screw head half, as the thread doesn't need to bite into the plastic on that half. But being perfectly honest I don't know much about git. Can I modify this PR with updated files, or do I need to close this and submit a new one?

**Comment by jakemcivor** [comment]
This aid is intended to break the seal on a jar to make it easier to open. It functions sort of like a bottle cap opener I believe, mostly intended for something like a jam jar with an thin metal seal under the lid, but apparently useful for integrated lids as well. 

You should be able to add additional changes by pushing commits to your main branch. No new pull request required.

I like the idea of creating a variant here - there is an advantage to keeping a version that is a single 3D printed part, even if it requires some support. 

There are standard values for the hole sizes of the counter bore, pilot hole, and pre-tap/self-tapping portion of a bolted/screwed connection like this:  
Counterbore Hole

See, for example, https://engineersbible.com/counterbore-socket-ansi-metric/ . For an M3 cap screws, a normal fit pilot hole diameter would be 3.4 mm and counterbore diameter would be 6.5 mm. Note that these are for traditional manufacturing, so you may need to add some extra clearance to accommodate for the 3d printer tolerance.

There are also some best practices for threading into 3D printed parts. In this case, where the screws are self tapping into plastic, one best practice / rule of thumb is 96% of the nominal thread diameter (i.e., 0.96*3 mm = 2.88 mm). (See https://www.hydraresearch3d.com/design-rules#threads-post-process) 

Could also consider using a hex nut here - either inserted from the other side of the hole or via a slot in the side. The print orientation would work best with a hexagonal slot, but not sure how that might affect the comfort of the handle.

**Comment by Myles512** [comment]
Sorry for the delay. I believe the tiny lip that fits under the jar's lid could maybe be strengthened, but I'll need to do some more testing. So far I have been unable to locate any sealed jars that I can open. :)

**Pull request merged**
